"""add pdf_template_name to user

Revision ID: 93b5b14544e8
Revises: 
Create Date: 2025-07-11 22:48:52.146089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b5b14544e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamento', sa.Column('cliente_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orcamento', 'cliente', ['cliente_id'], ['id'])
    op.drop_column('orcamento', 'endereco')
    op.drop_column('orcamento', 'nome')
    op.drop_column('orcamento', 'telefone')
    op.add_column('user', sa.Column('pdf_template_name', sa.String(), nullable=False, server_default="default"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'pdf_template_name')
    op.add_column('orcamento', sa.Column('telefone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orcamento', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('orcamento', sa.Column('endereco', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orcamento', type_='foreignkey')
    op.drop_column('orcamento', 'cliente_id')
    # ### end Alembic commands ###
